export const cards = [
  {
    id: 1,
    title: "Rosie's Garden",
    dimensions: "24 x 30",
    price: 420,
    status: "Available",
    printPrice: null,
    gicleePrice: 249,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/Roses-Garden-24x30_1.jpg",
    className: "md:col-span-2",
  },
  {
    id: 2,
    title: "Standing Tall",
    dimensions: "24 x 24",
    price: 320,
    status: "Sold",
    printPrice: null,
    gicleePrice: 175,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/kent_hepburns-flowers-2_640px-1.jpg",
    className: "col-span-1",
  },
  {
    id: 3,
    title: "Lily",
    dimensions: "30 x 30",
    price: 590,
    status: "Available",
    printPrice: null,
    gicleePrice: 290,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/Pink-Water-Lily-30x30-2.jpg",
    className: "col-span-1",
  },
  {
    id: 4,
    title: "Blue Vase",
    dimensions: "30 x 40",
    price: 590,
    status: "Available",
    printPrice: null,
    gicleePrice: null,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/Blue-Vase-30x40-lower-res.jpg",
    className: "md:col-span-2",
  },
  {
    id: 5,
    title: "Night Flowers",
    dimensions: "24 x 24",
    price: 390,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/Night-Flowers-23.75-x-24-lower-res.jpg",
    className: "md:col-span-2",
  },
  {
    id: 6,
    title: "Tulip Chaos",
    dimensions: "24 x 30",
    price: 420,
    status: "Available",
    printPrice: null,
    gicleePrice: null,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/Tulip-Chaos-24x30-MediiumRes.jpg",
    className: "col-span-1",
  },
  {
    id: 7,
    title: "Artists by the River",
    dimensions: "24 x 30",
    price: 420,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/Artists-by-the-River-10.25x7_2.jpg",
    className: "col-span-1",
  },
  {
    id: 8,
    title: "Primary Pots",
    dimensions: "18 x 36",
    price: 420,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/Primary-Pots-36x18_2.jpg",
    className: "md:col-span-2",
  },
  {
    id: 9,
    title: "At the Dock",
    dimensions: "24 x 30",
    price: 420,
    status: "Available",
    printPrice: null,
    gicleePrice: null,
    style: "Acrylic",
    thumbnail: "/images/portfolio/At-the-Dock-24x30-1.jpg",
    className: "md:col-span-2",
  },
  {
    id: 10,
    title: "Evening in Budapest",
    dimensions: "12 x 36",
    price: 320,
    status: "Sold",
    printPrice: null,
    gicleePrice: 175,
    style: "Acrylic",
    thumbnail: "/images/portfolio/Evening-in-Budapest-V2-12x36-MediumRes.jpg",
    className: "col-span-1",
  },
  {
    id: 11,
    title: "Poppy Chaos",
    dimensions: "24 x 30",
    price: 420,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/poppy.jpg",
    className: "col-span-1",
  },
  {
    id: 12,
    title: "Cabbage I",
    dimensions: "18 x 24",
    price: 290,
    status: "Available",
    printPrice: 129,
    gicleePrice: null,
    style: "Oil Pastels",
    thumbnail: "/images/portfolio/caba1.webp",
    className: "md:col-span-2",
  },
  {
    id: 13,
    title: "Cabbage II",
    dimensions: "18 x 24",
    price: 290,
    status: "Sold",
    printPrice: 129,
    gicleePrice: null,
    style: "Oil Pastels",
    thumbnail: "/images/portfolio/cab2.webp",
    className: "md:col-span-2",
  },
  {
    id: 14,
    title: "Cabbage III",
    dimensions: "18 x 24",
    price: 290,
    status: "Available",
    printPrice: 129,
    gicleePrice: null,
    style: "Oil Pastels",
    thumbnail: "/images/portfolio/caba3.webp",
    className: "col-span-1",
  },
  {
    id: 15,
    title: "Acropolis I",
    dimensions: "24 x 30",
    price: 420,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/acro1.webp",
    className: "col-span-1",
  },
  {
    id: 16,
    title: "Acropolis II",
    dimensions: "24 x 30",
    price: 420,
    status: "Available",
    printPrice: null,
    gicleePrice: 249,
    style: "Original",
    thumbnail: "/images/portfolio/acro2.webp",
    className: "md:col-span-2",
  },
  {
    id: 17,
    title: "Three Poppy Pods",
    dimensions: "24 x 24",
    price: 390,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/poppie.webp",
    className: "md:col-span-2",
  },
  {
    id: 18,
    title: "Precocious Poppies I",
    dimensions: "24 x 30",
    price: 420,
    status: "Available",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/prepoppies.webp",
    className: "col-span-1",
  },
  {
    id: 19,
    title: "Precocious Poppies II",
    dimensions: "12 x 36",
    price: 390,
    status: "Sold",
    printPrice: 390,
    gicleePrice: 220,
    style: "Acrylic",
    thumbnail: "/images/portfolio/pre.webp",
    className: "col-span-1",
  },
  {
    id: 20,
    title: "White Poppy",
    dimensions: "24 x 30",
    price: 420,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: null,
    thumbnail: "/images/portfolio/whitepopp.webp",
    className: "md:col-span-2",
  },
  {
    id: 21,
    title: "Hepburn Flowers",
    dimensions: "24 x 30",
    price: 420,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/hep.webp",
    className: "md:col-span-2",
  },
  {
    id: 22,
    title: "African Sunset",
    dimensions: "30 x 40",
    price: 590,
    status: "Sold",
    printPrice: null,
    gicleePrice: 320,
    style: "Acrylic",
    thumbnail: "/images/portfolio/africa.webp",
    className: "col-span-1",
  },
  {
    id: 23,
    title: "Osaka Poppies",
    dimensions: "24 x 24",
    price: 390,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/osaka.webp",
    className: "col-span-1",
  },
  {
    id: 24,
    title: "Shanghai Poppies",
    dimensions: "24 x 30",
    price: 420,
    status: "Sold",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/shangai.webp",
    className: "md:col-span-2",
  },
  {
    id: 25,
    title: "What Fun",
    dimensions: "18 x 24",
    price: 290,
    status: "Sold",
    printPrice: 129,
    gicleePrice: null,
    style: "Acrylic",
    thumbnail: "/images/portfolio/fun.webp",
    className: "md:col-span-2",
  },
  {
    id: 26,
    title: "My Garden",
    dimensions: "22 x 28",
    price: 290,
    status: "Available",
    printPrice: 129,
    gicleePrice: null,
    style: "Acrylic",
    thumbnail: "/images/portfolio/gardennn.webp",
    className: "col-span-1",
  },
  {
    id: 27,
    title: "Poinsettia",
    dimensions: "22 x 28",
    price: 290,
    status: "Available",
    printPrice: 129,
    gicleePrice: null,
    style: "Oil Pastel",
    thumbnail: "/images/portfolio/poe.webp",
    className: "col-span-1",
  },
  {
    id: 28,
    title: "Lynn's Poppy",
    dimensions: "30 x 40",
    price: 590,
    status: "Sold",
    printPrice: null,
    gicleePrice: 320,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/lynpoppy.webp",
    className: "md:col-span-2",
  },
  {
    id: 29,
    title: "Nasturium",
    dimensions: "24 x 30",
    price: 420,
    status: "Available",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic Original",
    thumbnail: "/images/portfolio/nasturium.webp",
    className: "md:col-span-2",
  },
  {
    id: 30,
    title: "The Cycle",
    dimensions: "18 x 24",
    price: 320,
    status: "Available",
    printPrice: 129,
    gicleePrice: null,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/The-Cycle-5x7-cards.webp",
    className: "col-span-1",
  },
  {
    id: 31,
    title: "Sunny Sunflowers",
    dimensions: "24 x 24",
    price: 390,
    status: "Available",
    printPrice: null,
    gicleePrice: null,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/92194682-3737-48C5-A54D-0905EAE28C7F.webp",
    className: "col-span-1",
  },
  {
    id: 32,
    title: "Lilly in Red",
    dimensions: "30 x 30",
    price: 590,
    status: "Available",
    printPrice: null,
    gicleePrice: null,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/Lilly-in-Red-30x30-2.jpg",
    className: "md:col-span-2",
  },
  {
    id: 33,
    title: "Dennis the Menace",
    dimensions: "20 x 30",
    price: 420,
    status: "Available",
    printPrice: null,
    gicleePrice: null,
    style: "Mixed Media",
    thumbnail: "/images/portfolio/Dennis-the-Menace-24x30-1.jpg",
    className: "md:col-span-2",
  },
  {
    id: 34,
    title: "Sicily Olive Grove",
    dimensions: "36 x 18",
    price: 420,
    status: "Available",
    printPrice: null,
    gicleePrice: 249,
    style: "Acrylic",
    thumbnail: "/images/portfolio/Sicilys-Olive-Grove-36x18-1.jpg",
    className: "col-span-1",
  },
  {
    id: 35,
    title: "Sienna Nude",
    dimensions: "17 x 12",
    price: null,
    status: "Sold",
    printPrice: 129,
    gicleePrice: null,
    style: "Oil paint",
    thumbnail: "/images/portfolio/Sienne-Nude-17.24-x-12.75-1.png",
    className: "col-span-1",
  },
];
